---
title-block: false
format:
  html:
    smooth-scroll: true
    theme: materia
    page-layout: full
    fontsize: 0.8em
    toc: true
    toc-location: body
    embed-resources: true
params:
  core_project: "OT2OD030545"
title: "Core Project {{< meta params.core_project >}}"
---

```{r}
#| label: setup
#| echo: false
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(programets))
suppressPackageStartupMessages(library(DT))

# Positron IDE fix
if(interactive()) {params <- list(core_project = "OT2OD030545")}

# Load Project Info
proj_info <- get_core_project_info(c(params$core_project, "99999999")) %>% 
    filter(core_project_num != '99999999')
icite_info <- programets::icite(proj_info$pmid)
proj_info %<>% 
    left_join(icite_info, by = c('pmid' = '_id'))
git_info <- get_github_by_topic(topics = params$core_project, token = gitcreds::gitcreds_get()$password, limit = 150)
```

## Details

```{r}
#| label: details
#| echo: false
projects <- proj_info %>% distinct(project_num)
name <- proj_info %>% distinct(project_title)
total_direct_cost <- proj_info %>% distinct(direct_cost_amt, project_num) %>% pull(direct_cost_amt) %>% sum(na.rm = TRUE)
total_indirect_cost <- proj_info %>% distinct(indirect_cost_amt, project_num) %>% pull(indirect_cost_amt) %>% sum(na.rm = TRUE)
award <- total_direct_cost + total_indirect_cost
publications <- proj_info %>% filter(!is.na(pmid)) %>% distinct(pmid) %>% count()
repos <- git_info %>% count()
open_issues <- git_info %>% pull(open_issues) %>% sum(na.rm = TRUE)
closed_issues <- git_info %>% pull(closed_issues) %>% sum(na.rm = TRUE)
open_prs <- git_info %>% pull(open_prs) %>% sum(na.rm = TRUE)
closed_prs <- git_info %>% pull(closed_prs) %>% sum(na.rm = TRUE)
stars <- git_info %>% pull(stars) %>% sum(na.rm = TRUE)
watchers <- git_info %>% pull(watchers) %>% sum(na.rm = TRUE)
forks <- git_info %>% pull(forks) %>% sum(na.rm = TRUE)
commits <- git_info %>% pull(commits) %>% sum(na.rm = TRUE)
contributors <- git_info %>% pull(contributors) %>% sum(na.rm = TRUE)
```


```{r}
#| label: details-display
#| echo: false

## Projects
dt_projects <- datatable(
  projects %>% 
    rename(Projects = project_num),
  options = list(dom = 't', paging = FALSE, ordering = FALSE),
  rownames = FALSE
)

## Name
dt_name <- datatable(
  name %>% 
    rename(Name = project_title),
  options = list(dom = 't', paging = FALSE, ordering = FALSE),
  rownames = FALSE
)

## Publications
dt_publications <- datatable(
  publications %>% 
    mutate(n = glue::glue("{n} publications")) %>% 
    rename('Publications' = n),
  options = list(dom = 't', paging = FALSE, ordering = FALSE),
  rownames = FALSE
)

## Award
dt_name_award <- datatable(
  tibble::tibble(
    Award = award
    ),
  options = list(dom = 't', paging = FALSE, ordering = FALSE),
  rownames = FALSE
  ) %>% 
  formatCurrency(
    columns = "Award",
    currency = "$",
    interval = 3,
    mark = ",",
    digits = 2
  )

## Repositories
dt_repos <- datatable(
  repos %>% 
    mutate(n = glue::glue("{format(n, big.mark = ',')} repositories")) %>% 
    rename('Repositories' = n) %>% 
    add_row(Repositories = glue::glue("{format(stars, big.mark = ',')} stars")) %>% 
    add_row(Repositories = glue::glue("{format(watchers, big.mark = ',')} watchers")) %>% 
    add_row(Repositories = glue::glue("{format(forks, big.mark = ',')} forks")) %>% 
    add_row(Repositories = glue::glue("{format(sum(open_issues, closed_issues), big.mark = ',')} issues")) %>% 
    add_row(Repositories = glue::glue("{format(sum(open_prs, closed_prs), big.mark = ',')} pull requests")) %>% 
    add_row(Repositories = glue::glue("{format(commits, big.mark = ',')} commits")) %>% 
    add_row(Repositories = glue::glue("{format(contributors, big.mark = ',')} contributors")),
  options = list(dom = 't', paging = FALSE, ordering = FALSE),
  rownames = FALSE
  ) 

## Arrange in Report
htmltools::browsable(
  htmltools::tagList(
    htmltools::tags$div(
      style = "display: flex; gap: 20px;",
      htmltools::tags$div(style = "width: 25%;", dt_projects),
      htmltools::tags$div(style = "width: 25%;", dt_name),
      htmltools::tags$div(style = "width: 25%;", dt_name_award)
    ),
    htmltools::tags$div(
      style = "display: flex; gap: 20px; margin-top: 20px;",
      htmltools::tags$div(style = "width: 25%;", dt_publications),
      htmltools::tags$div(style = "width: 25%;", dt_repos)
    )
  )
)
```

## Publications

```{r}
#| label: publications
#| echo: false

proj_info %>% 
  filter(found_publication == TRUE) %>% 
  mutate(
      pubmed_url = glue::glue("<a href='https://pubmed.ncbi.nlm.nih.gov/{pmid}' target='_blank'>{pmid}</a>"),
      doi_url = glue::glue("<a href='https://doi.org/{doi}' target='_blank'>DOI</a>"),
      ID = glue::glue("{pubmed_url}<br>{doi_url}"),
      Authors = map_chr(authors, ~ str_c(.x$lastName, collapse = ", ")),
      RCR = round(relative_citation_ratio, 2)
  ) %>% 
  mutate(across(where(is.numeric), ~ replace_na(.x, 0))) %>% 
  select(ID, Title = title, Authors, RCR, Citations = citation_count, 'Citations/Year' = citations_per_year, Journal = journal, Published = year, Updated = date_added) %>% 
  datatable(
    extensions = 'Buttons', 
    options = list(
      dom = 'Bfrtip',
      buttons = c('csv', 'excel'),
      scrollY = 500,
      scroller = TRUE
    ),
    rownames = FALSE,
    escape = FALSE
  )
```

## Repositories

```{r}
#| label: repos
#| echo: false
git_info %>% 
  mutate(
    Name = glue::glue("<a href='{html_url}' target='_blank'>{owner}/{name}</a>"),
    closed_issues_chr = glue::glue("Closed: {closed_issues}"),
    open_issues_chr = glue::glue("Open: {open_issues}"),
    Issues = glue::glue("{closed_issues_chr}<br>{open_issues_chr}"),
    closed_prs_chr = glue::glue("Closed: {closed_prs}"),
    open_prs_chr = glue::glue("Open: {open_prs}"),
    PRs = glue::glue("{closed_prs_chr}<br>{open_prs_chr}")
  ) %>%
  mutate(across(where(is.numeric), ~ replace_na(.x, 0))) %>% 
  mutate(across(where(is.character), ~ replace_na(.x, '-'))) %>% 
  select(
    Name, Description = description, Stars = stars, Watchers = watchers, Forks = forks, Issues, PRs,
    Commits = commits, Contrib. = contributors, Tags = tags, Languages = language, License = license
    ) %>% 
  datatable(
    extensions = 'Buttons', 
    options = list(
      dom = 'Bfrtip',
      buttons = c('csv', 'excel'),
      scrollY = 500,
      scroller = TRUE
    ),
    rownames = FALSE,
    escape = FALSE
  )
```